"use client";

import { addMeal, updateMeal } from "@/lib/actions/meals";
import { generateIngredientDraftClient, type IngredientDraftItem } from "@/lib/ai/ingredients-client";
import { generateDishImageUrl } from "@/lib/image-generation/client";
import { resolveMealImageUrl } from "@/lib/meal-image-url";
import { Loader2, Plus, Sparkles, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Meal = {
  id: string;
  name: string;
  sourceCommonMealId?: string | null;
  complexity: "SIMPLE" | "MEDIUM" | "COMPLEX";
  defaultServings?: number;
  preferredDays: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[];
  imageUrl: string | null;
  ingredients?: unknown;
  mealIngredients?: Array<{
    name: string;
    amount: number | null;
    unit: string | null;
    note: string | null;
    optional: boolean;
    confidence: number | null;
    needsReview: boolean;
  }>;
};

type EditorMode = { type: "create" } | { type: "edit"; meal: Meal };
type StarterDraft = {
  sourceCommonMealId: string;
  name: string;
  complexity: Meal["complexity"];
  imageUrl: string | null;
};

const DAY_OPTIONS = [
  { value: "MONDAY",    short: "M", label: "Måndag"  },
  { value: "TUESDAY",   short: "T", label: "Tisdag"  },
  { value: "WEDNESDAY", short: "O", label: "Onsdag"  },
  { value: "THURSDAY",  short: "T", label: "Torsdag" },
  { value: "FRIDAY",    short: "F", label: "Fredag"  },
  { value: "SATURDAY",  short: "L", label: "Lördag"  },
  { value: "SUNDAY",    short: "S", label: "Söndag"  },
] as const;

type PreferredDay = (typeof DAY_OPTIONS)[number]["value"];
type GenerationStatus = "idle" | "loading" | "success" | "error";

const COMPLEXITY_OPTIONS: Array<{ value: Meal["complexity"]; label: string; color: string; active: string }> = [
  { value: "SIMPLE",  label: "Enkel",     color: "text-emerald-400/60", active: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30" },
  { value: "MEDIUM",  label: "Medium",    color: "text-amber-400/60",   active: "bg-amber-500/15 text-amber-300 border-amber-500/30"       },
  { value: "COMPLEX", label: "Avancerad", color: "text-red-400/60",     active: "bg-red-500/15 text-red-300 border-red-500/30"             },
];

function mapMealIngredients(meal?: Meal): IngredientDraftItem[] {
  if (!meal) return [];
  if (!meal.mealIngredients || meal.mealIngredients.length === 0) {
    const legacy = Array.isArray(meal.ingredients)
      ? meal.ingredients
          .filter((v): v is string => typeof v === "string" && v.trim().length > 0)
          .map((name) => ({ name: name.trim(), amount: null, unit: null, note: null, optional: false, confidence: null, needsReview: true }))
      : [];
    return legacy;
  }
  return meal.mealIngredients.map((i) => ({
    name: i.name, amount: i.amount, unit: i.unit, note: i.note,
    optional: i.optional, confidence: i.confidence, needsReview: i.needsReview,
  }));
}

export function MealEditorSheet({
  mode,
  isOpen,
  onClose,
  onSaved,
  autoGenerateDraftOnOpen = false,
  reviewHint,
  initialCreateValues,
}: {
  mode: EditorMode;
  isOpen: boolean;
  onClose: () => void;
  onSaved?: () => void;
  autoGenerateDraftOnOpen?: boolean;
  reviewHint?: string | null;
  initialCreateValues?: StarterDraft | null;
}) {
  const router = useRouter();
  const [name, setName] = useState("");
  const [complexity, setComplexity] = useState<Meal["complexity"]>("MEDIUM");
  const [defaultServings, setDefaultServings] = useState(4);
  const [preferredDays, setPreferredDays] = useState<PreferredDay[]>([]);
  const [ingredients, setIngredients] = useState<IngredientDraftItem[]>([]);
  const [imageMode, setImageMode] = useState<"upload" | "url">("upload");
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imageUrl, setImageUrl] = useState("");
  const [imageUrlExpanded, setImageUrlExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [ingredientLoading, setIngredientLoading] = useState(false);
  const [imageLoading, setImageLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [previewError, setPreviewError] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [autoGeneratedMealId, setAutoGeneratedMealId] = useState<string | null>(null);
  const [ingredientGenerationStatus, setIngredientGenerationStatus] = useState<GenerationStatus>("idle");
  const [ingredientGenerationMessage, setIngredientGenerationMessage] = useState<string | null>(null);
  const [imageGenerationStatus, setImageGenerationStatus] = useState<GenerationStatus>("idle");
  const [imageGenerationMessage, setImageGenerationMessage] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    if (mode.type === "create") {
      setName(initialCreateValues?.name ?? "");
      setComplexity(initialCreateValues?.complexity ?? "MEDIUM");
      setDefaultServings(4);
      setPreferredDays([]); setIngredients([]);
      setImageMode(initialCreateValues?.imageUrl ? "url" : "upload");
      setImageFile(null);
      setImageUrl(initialCreateValues?.imageUrl ?? "");
    } else {
      setName(mode.meal.name);
      setComplexity(mode.meal.complexity);
      setDefaultServings(Math.max(1, Math.min(12, Math.round(mode.meal.defaultServings ?? 4))));
      setPreferredDays(mode.meal.preferredDays);
      setIngredients(mapMealIngredients(mode.meal));
      setImageMode(mode.meal.imageUrl ? "url" : "upload");
      setImageFile(null);
      setImageUrl(mode.meal.imageUrl ?? "");
    }
    setImageUrlExpanded(false);
    setError(null);
    setPreviewError(false);
    setIngredientGenerationStatus("idle");
    setIngredientGenerationMessage(null);
    setImageGenerationStatus("idle");
    setImageGenerationMessage(null);
  }, [initialCreateValues, isOpen, mode]);

  useEffect(() => {
    if (!imageFile) { setPreviewUrl(null); return; }
    const blobUrl = URL.createObjectURL(imageFile);
    setPreviewUrl(blobUrl);
    return () => URL.revokeObjectURL(blobUrl);
  }, [imageFile]);

  useEffect(() => {
    if (!isOpen || !autoGenerateDraftOnOpen) {
      return;
    }
    const generationKey =
      mode.type === "edit"
        ? mode.meal.id
        : initialCreateValues?.sourceCommonMealId
          ? `starter-${initialCreateValues.sourceCommonMealId}`
          : null;
    if (!generationKey) {
      return;
    }
    if (autoGeneratedMealId === generationKey) {
      return;
    }
    const dishName = mode.type === "edit" ? mode.meal.name.trim() : (initialCreateValues?.name ?? "").trim();
    if (!dishName) {
      return;
    }

    let active = true;
    setAutoGeneratedMealId(generationKey);
    void (async () => {
      try {
        setIngredientGenerationStatus("loading");
        setIngredientGenerationMessage("Genererar ingrediensförslag automatiskt…");
        setIngredientLoading(true);
        const draft = await generateIngredientDraftClient(dishName);
        if (active && draft.ingredients.length > 0) {
          setIngredients(draft.ingredients);
          setIngredientGenerationStatus("success");
          setIngredientGenerationMessage("Ingrediensförslag klara.");
        } else if (active) {
          setIngredientGenerationStatus("error");
          setIngredientGenerationMessage("Kunde inte generera ingrediensförslag automatiskt.");
        }
      } catch (generationError) {
        if (active) {
          setIngredientGenerationStatus("error");
          setIngredientGenerationMessage(
            generationError instanceof Error
              ? generationError.message
              : "Kunde inte generera ingrediensförslag automatiskt.",
          );
        }
      } finally {
        if (active) {
          setIngredientLoading(false);
        }
      }

      try {
        setImageGenerationStatus("loading");
        setImageGenerationMessage("Genererar bild automatiskt…");
        setImageLoading(true);
        const generated = await generateDishImageUrl(dishName);
        if (active) {
          setImageMode("url");
          setImageFile(null);
          setImageUrl(generated.imageUrl);
          setPreviewError(false);
          setImageGenerationStatus("success");
          setImageGenerationMessage("Bildgenerering klar.");
        }
      } catch (generationError) {
        if (active) {
          setImageGenerationStatus("error");
          setImageGenerationMessage(
            generationError instanceof Error ? generationError.message : "Kunde inte generera bild automatiskt.",
          );
        }
      } finally {
        if (active) {
          setImageLoading(false);
        }
      }
    })();

    return () => {
      active = false;
    };
  }, [autoGenerateDraftOnOpen, autoGeneratedMealId, initialCreateValues, isOpen, mode]);

  function applyDayPreset(preset: "weekday" | "friday" | "weekend") {
    if (preset === "weekday") { setPreferredDays(["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY"]); return; }
    if (preset === "friday") { setPreferredDays(["FRIDAY"]); return; }
    setPreferredDays(["SATURDAY", "SUNDAY"]);
  }

  async function handleGenerateIngredients() {
    const dishName = name.trim();
    if (!dishName || ingredientLoading) return;
    setIngredientGenerationStatus("loading");
    setIngredientGenerationMessage("Genererar ingrediensförslag…");
    setIngredientLoading(true);
    setError(null);
    try {
      const draft = await generateIngredientDraftClient(dishName);
      setIngredients(draft.ingredients);
      setIngredientGenerationStatus("success");
      setIngredientGenerationMessage("Ingrediensförslag uppdaterade.");
    } catch (err) {
      setIngredientGenerationStatus("error");
      setIngredientGenerationMessage(err instanceof Error ? err.message : "Kunde inte generera ingredienser.");
      setError(err instanceof Error ? err.message : "Kunde inte generera ingredienser.");
    } finally {
      setIngredientLoading(false);
    }
  }

  async function handleGenerateImage() {
    const dishName = name.trim();
    if (!dishName || imageLoading) return;
    setImageGenerationStatus("loading");
    setImageGenerationMessage("Genererar bild…");
    setImageLoading(true);
    setError(null);
    try {
      const generated = await generateDishImageUrl(dishName);
      setImageMode("url");
      setImageFile(null);
      setImageUrl(generated.imageUrl);
      setPreviewError(false);
      setImageGenerationStatus("success");
      setImageGenerationMessage("Bilden är uppdaterad.");
    } catch (err) {
      setImageGenerationStatus("error");
      setImageGenerationMessage(err instanceof Error ? err.message : "Kunde inte generera bild.");
      setError(err instanceof Error ? err.message : "Kunde inte generera bild.");
    } finally {
      setImageLoading(false);
    }
  }

  async function handleSubmit() {
    const trimmedName = name.trim();
    if (!trimmedName || loading) return;
    setLoading(true);
    setError(null);
    try {
      const formData = new FormData();
      formData.append("name", trimmedName);
      formData.append("complexity", complexity);
      formData.append("defaultServings", String(defaultServings));
      for (const day of preferredDays) formData.append("preferredDays", day);
      const cleanedIngredients = ingredients
        .map((i) => ({ ...i, name: i.name.trim() }))
        .filter((i) => i.name.length > 0);
      if (cleanedIngredients.length > 0) formData.append("ingredients", JSON.stringify(cleanedIngredients));
      if (imageMode === "upload" && imageFile) formData.append("image", imageFile);
      if (imageMode === "url" && imageUrl.trim()) formData.append("imageUrl", imageUrl.trim());
      if (mode.type === "create" && initialCreateValues?.sourceCommonMealId) {
        formData.append("sourceCommonMealId", initialCreateValues.sourceCommonMealId);
      }
      const result =
        mode.type === "create" ? await addMeal(formData) : await updateMeal(mode.meal.id, formData);
      if (result.error) { setError(result.error); return; }
      onSaved?.();
      onClose();
      router.refresh();
    } catch {
      setError("Kunde inte spara måltiden. Försök igen.");
    } finally {
      setLoading(false);
    }
  }

  const currentImageSrc = previewUrl ?? (imageMode === "url" && imageUrl.trim()
    ? resolveMealImageUrl(imageUrl, name || "Meal preview")
    : null);

  return (
    <div
      className={`absolute inset-0 z-20 bg-[#0e0e0e] transition-transform duration-300 ${
        isOpen ? "translate-x-0" : "translate-x-full"
      }`}
      aria-hidden={!isOpen}
    >
      <div className="flex h-full flex-col">
        {/* Header */}
        <header className="flex shrink-0 items-center justify-between border-b border-white/[0.06] px-5 py-4">
          <div>
            <p className="text-[9px] font-bold uppercase tracking-[0.45em] text-white/25">
              {mode.type === "create" ? "Ny måltid" : "Redigera"}
            </p>
            <h3 className="text-xl font-bold text-white">
              {name.trim() || (mode.type === "create" ? "Namnlös" : "Måltid")}
            </h3>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-full text-white/40 transition hover:bg-white/8 hover:text-white"
            aria-label="Stäng editor"
          >
            <X className="h-4 w-4" />
          </button>
        </header>

        {/* Image strip — top of form */}
        <div className="relative shrink-0">
          {currentImageSrc && !previewError ? (
            <div className="relative h-40 bg-black">
              <img
                src={currentImageSrc}
                alt={name || "Förhandsgranskning"}
                className="h-full w-full object-cover opacity-80"
                loading="lazy"
                referrerPolicy="no-referrer"
                onError={() => setPreviewError(true)}
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#0e0e0e]/80 to-transparent" />
            </div>
          ) : (
            <div className="flex h-24 items-center justify-center border-b border-white/[0.06] bg-white/[0.02]">
              <p className="text-xs text-white/20">Ingen bild vald</p>
            </div>
          )}
          {/* Image action buttons overlay */}
          <div className="absolute right-3 bottom-3 flex gap-2">
            <button
              type="button"
              onClick={() => void handleGenerateImage()}
              disabled={imageLoading || !name.trim()}
              className="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-black/60 px-3 py-1.5 text-[11px] font-semibold text-white/70 backdrop-blur-sm transition hover:border-white/35 hover:text-white disabled:opacity-40"
            >
              {imageLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
              {imageLoading ? "Genererar…" : "Generera"}
            </button>
            <label className="inline-flex cursor-pointer items-center gap-1.5 rounded-full border border-white/20 bg-black/60 px-3 py-1.5 text-[11px] font-semibold text-white/70 backdrop-blur-sm transition hover:border-white/35 hover:text-white">
              Ladda upp
              <input
                type="file"
                accept="image/*"
                onChange={(e) => {
                  setImageMode("upload");
                  setImageFile(e.target.files?.[0] ?? null);
                  setPreviewError(false);
                }}
                className="hidden"
              />
            </label>
          </div>
        </div>

        {/* Form body */}
        <div className="dark-inputs flex-1 overflow-y-auto px-5 py-5">
          <div className="space-y-6">
            {reviewHint && (
              <div className="space-y-3 rounded-xl border border-amber-500/20 bg-amber-500/10 px-4 py-3">
                <p className="text-xs font-medium text-amber-200">{reviewHint}</p>
                <div className="flex flex-wrap gap-2">
                  <button
                    type="button"
                    onClick={() => void handleGenerateIngredients()}
                    disabled={ingredientLoading || !name.trim()}
                    className="inline-flex items-center gap-1.5 rounded-full border border-amber-400/40 px-3 py-1 text-[11px] font-semibold text-amber-100 transition hover:bg-amber-500/20 disabled:opacity-50"
                  >
                    {ingredientLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                    Generera ingredienser igen
                  </button>
                  <button
                    type="button"
                    onClick={() => void handleGenerateImage()}
                    disabled={imageLoading || !name.trim()}
                    className="inline-flex items-center gap-1.5 rounded-full border border-amber-400/40 px-3 py-1 text-[11px] font-semibold text-amber-100 transition hover:bg-amber-500/20 disabled:opacity-50"
                  >
                    {imageLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                    Generera bild igen
                  </button>
                </div>
                <div className="space-y-1 text-[11px] text-amber-100/90">
                  {ingredientGenerationMessage && (
                    <p>
                      Ingredienser:{" "}
                      <span
                        className={
                          ingredientGenerationStatus === "error" ? "text-red-200" : "text-amber-100/90"
                        }
                      >
                        {ingredientGenerationMessage}
                      </span>
                    </p>
                  )}
                  {imageGenerationMessage && (
                    <p>
                      Bild:{" "}
                      <span
                        className={imageGenerationStatus === "error" ? "text-red-200" : "text-amber-100/90"}
                      >
                        {imageGenerationMessage}
                      </span>
                    </p>
                  )}
                </div>
              </div>
            )}

            {/* Name */}
            <div>
              <p className="mb-2 text-[9px] font-bold uppercase tracking-[0.4em] text-white/25">Namn</p>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Måltidsnamn"
                className="w-full rounded-xl border border-white/[0.08] bg-white/[0.04] px-4 py-3 text-lg font-semibold text-white placeholder-white/20 focus:border-[var(--terracotta)] focus:outline-none focus:ring-2 focus:ring-[var(--terracotta)]/20"
                style={{ background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)" }}
              />
            </div>

            {/* Complexity */}
            <div>
              <p className="mb-2 text-[9px] font-bold uppercase tracking-[0.4em] text-white/25">Komplexitet</p>
              <div className="flex gap-2">
                {COMPLEXITY_OPTIONS.map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    onClick={() => setComplexity(option.value)}
                    className={`flex-1 rounded-xl border py-2.5 text-xs font-semibold transition ${
                      complexity === option.value
                        ? option.active
                        : "border-white/[0.08] bg-white/[0.03] text-white/35 hover:bg-white/[0.06]"
                    }`}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Servings */}
            <div>
              <p className="mb-2 text-[9px] font-bold uppercase tracking-[0.4em] text-white/25">Portioner</p>
              <div className="inline-flex items-center gap-3 rounded-xl border border-white/[0.08] bg-white/[0.03] px-4 py-2.5">
                <button
                  type="button"
                  onClick={() => setDefaultServings((n) => Math.max(1, n - 1))}
                  className="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.1] text-sm font-bold text-white/50 transition hover:bg-white/[0.07] hover:text-white"
                >
                  −
                </button>
                <span className="min-w-[4rem] text-center text-sm font-semibold text-white/80">
                  {defaultServings} pers
                </span>
                <button
                  type="button"
                  onClick={() => setDefaultServings((n) => Math.min(12, n + 1))}
                  className="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.1] text-sm font-bold text-white/50 transition hover:bg-white/[0.07] hover:text-white"
                >
                  +
                </button>
              </div>
              <p className="mt-1.5 text-[11px] text-white/25">Ingredienserna gäller för denna mängd.</p>
            </div>

            {/* Preferred days */}
            <div>
              <p className="mb-2 text-[9px] font-bold uppercase tracking-[0.4em] text-white/25">Passar bäst</p>
              <div className="flex flex-wrap gap-2">
                {DAY_OPTIONS.map((dayOption) => {
                  const selected = preferredDays.includes(dayOption.value);
                  return (
                    <button
                      key={dayOption.value}
                      aria-label={dayOption.label}
                      type="button"
                      onClick={() =>
                        setPreferredDays((current) =>
                          current.includes(dayOption.value)
                            ? current.filter((d) => d !== dayOption.value)
                            : [...current, dayOption.value],
                        )
                      }
                      className={`flex h-9 w-9 items-center justify-center rounded-full border text-xs font-bold transition ${
                        selected
                          ? "border-[var(--terracotta)] bg-[var(--terracotta)] text-white"
                          : "border-white/[0.1] bg-white/[0.03] text-white/35 hover:border-white/20 hover:text-white/60"
                      }`}
                    >
                      {dayOption.short}
                    </button>
                  );
                })}
              </div>
              <div className="mt-2 flex items-center gap-4 text-[11px] font-semibold text-white/25">
                <button type="button" onClick={() => applyDayPreset("friday")}  className="transition hover:text-white/60">Fredagsmys</button>
                <button type="button" onClick={() => applyDayPreset("weekday")} className="transition hover:text-white/60">Vardag</button>
                <button type="button" onClick={() => applyDayPreset("weekend")} className="transition hover:text-white/60">Helg</button>
              </div>
            </div>

            {/* Ingredients */}
            <div>
              <div className="mb-3 flex items-center justify-between">
                <p className="text-[9px] font-bold uppercase tracking-[0.4em] text-white/25">Ingredienser</p>
                <button
                  type="button"
                  onClick={() => void handleGenerateIngredients()}
                  disabled={ingredientLoading || !name.trim()}
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-white/35 transition hover:text-white/70 disabled:opacity-40"
                >
                  {ingredientLoading
                    ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    : <Sparkles className="h-3.5 w-3.5" />}
                  {ingredientLoading ? "Genererar…" : "Generera förslag"}
                </button>
              </div>

              {ingredients.length > 0 && (
                <div className="mb-2 grid grid-cols-[1fr_68px_60px_32px] gap-1.5 px-1 text-[9px] font-bold uppercase tracking-[0.1em] text-white/20">
                  <span>Ingrediens</span>
                  <span>Mängd</span>
                  <span>Enhet</span>
                  <span />
                </div>
              )}

              <div className="space-y-1.5">
                {ingredients.map((ingredient, index) => (
                  <div key={index} className="grid grid-cols-[1fr_68px_60px_32px] gap-1.5">
                    <input
                      value={ingredient.name}
                      onChange={(e) => setIngredients((s) => s.map((item, i) => i === index ? { ...item, name: e.target.value } : item))}
                      placeholder="Ingrediens"
                      className="rounded-lg border border-white/[0.08] bg-white/[0.04] px-2.5 py-2 text-sm text-white placeholder-white/20 focus:border-[var(--terracotta)]/50 focus:outline-none"
                      style={{ background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)" }}
                    />
                    <input
                      type="number"
                      step="0.1"
                      value={ingredient.amount ?? ""}
                      onChange={(e) => setIngredients((s) => s.map((item, i) => i === index ? { ...item, amount: e.target.value ? Number(e.target.value) : null } : item))}
                      placeholder="—"
                      className="rounded-lg border border-white/[0.08] bg-white/[0.04] px-2.5 py-2 text-sm text-white placeholder-white/20 focus:border-[var(--terracotta)]/50 focus:outline-none"
                      style={{ background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)" }}
                    />
                    <input
                      value={ingredient.unit ?? ""}
                      onChange={(e) => setIngredients((s) => s.map((item, i) => i === index ? { ...item, unit: e.target.value || null } : item))}
                      placeholder="—"
                      className="rounded-lg border border-white/[0.08] bg-white/[0.04] px-2.5 py-2 text-sm text-white placeholder-white/20 focus:border-[var(--terracotta)]/50 focus:outline-none"
                      style={{ background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)" }}
                    />
                    <button
                      type="button"
                      onClick={() => setIngredients((s) => s.filter((_, i) => i !== index))}
                      className="flex h-9 w-8 items-center justify-center rounded-lg text-white/20 transition hover:bg-red-500/10 hover:text-red-400"
                      aria-label="Ta bort rad"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                    {ingredient.needsReview && (
                      <p className="col-span-4 pl-1 text-[10px] text-amber-500/60">Behöver granskning</p>
                    )}
                  </div>
                ))}
              </div>

              <div className="mt-2 flex items-center gap-4">
                <button
                  type="button"
                  onClick={() => setIngredients((s) => [...s, { name: "", amount: null, unit: null, note: null, optional: false, confidence: null, needsReview: false }])}
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-white/30 transition hover:text-white/60"
                >
                  <Plus className="h-3.5 w-3.5" />
                  Lägg till rad
                </button>
                {ingredients.length > 0 && (
                  <button
                    type="button"
                    onClick={() => setIngredients([])}
                    className="text-xs font-semibold text-red-400/40 transition hover:text-red-400"
                  >
                    Rensa alla
                  </button>
                )}
              </div>
            </div>

            {/* Image URL (expandable) */}
            <div>
              <button
                type="button"
                onClick={() => setImageUrlExpanded((v) => !v)}
                className="text-[11px] font-semibold text-white/25 transition hover:text-white/50"
              >
                {imageUrlExpanded ? "Dölj bild-URL" : "Ange bild-URL manuellt"}
              </button>
              {imageUrlExpanded && (
                <input
                  type="url"
                  value={imageUrl}
                  onChange={(e) => {
                    setImageMode("url");
                    setImageFile(null);
                    setImageUrl(e.target.value);
                    setPreviewError(false);
                  }}
                  placeholder="https://example.com/meal.jpg"
                  className="mt-2 w-full rounded-xl border border-white/[0.08] bg-white/[0.04] px-4 py-3 text-sm text-white placeholder-white/20 focus:border-[var(--terracotta)]/50 focus:outline-none"
                  style={{ background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)" }}
                />
              )}
            </div>

            {error && (
              <p className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-xs font-medium text-red-300">
                {error}
              </p>
            )}
          </div>
        </div>

        {/* Footer */}
        <footer className="shrink-0 border-t border-white/[0.06] bg-[#0e0e0e]/95 px-5 py-3 backdrop-blur">
          <div className="flex items-center justify-end gap-2">
            {reviewHint && (
              <p className="mr-auto text-[11px] font-medium text-white/35">
                Nästa steg: spara måltiden och byt in den i veckoplanen.
              </p>
            )}
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl border border-white/[0.08] px-4 py-2.5 text-xs font-semibold text-white/40 transition hover:bg-white/[0.05] hover:text-white/70"
            >
              {reviewHint ? "Stäng" : "Avbryt"}
            </button>
            <button
              type="button"
              onClick={() => void handleSubmit()}
              disabled={loading || !name.trim()}
              className="rounded-xl bg-[var(--terracotta)] px-5 py-2.5 text-xs font-semibold text-white shadow-lg shadow-[var(--terracotta)]/20 transition hover:bg-[var(--terracotta-dark)] disabled:opacity-50"
            >
              {loading ? "Sparar…" : reviewHint ? "Spara till mina måltider" : mode.type === "create" ? "Lägg till" : "Spara"}
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
